other:
    state: MongodbState   # state to use
    database: statedatabase     # defaults to microsoft bot framework
    app_client_id: f8dce41a-00a7-4cbf-87b6-959e2b41a8a2
app_client_secret: rrkqfbGI311^uQOPZK67^[;
mongodb:
    uri: mongodb://heroku_q377tj0m:q259mf7uovv4rktfg4vuc0401h@ds123796.mlab.com:23796/heroku_q377tj0m