version: '2.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatbot
    ports:  
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mongo
    container_name: mongodatabase
    volumes:
      - mongo-data:/data/db
      - ./docker/scripts:/scripts
      - ./docker/data:/data
    ports:  
      - "27017:27017"
    command: /bin/bash /scripts/populate.sh    
    healthcheck:
      test: ["CMD", "echo", ">", "/dev/tcp/localhost/27017", "||", "exit", "1"]
      interval: 40s
      timeout: 30s
      retries: 5